
language: php

php:
  - 7.2

before_script:
  - composer self-update
  # - pear install pear/PHP_CodeSniffer
  # - phpenv rehash
  - nvm install --lts
  - npm install npm@latest -g
  - cd src  
  - cp .env.example .env
  - composer install --no-interaction
  # - npm install
  
script: 
  # - phpcbf -v --standard=PSR2 app/Http/Controllers
  - find  app/Http/Controllers/ -type f -name '*.php' -exec php -l {} \; | (! grep -v "No syntax errors detected" )
  # - npm run production
 
cache:
  directories:
    - node_modules
    - vendor

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master

addons:
  ssh_known_hosts:
  - social.timbu.com