
language: php

php:
  - 7.2

before_script:
  - composer self-update
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install --lts
  - npm install npm@latest -g
  - cd src  
  - cp .env.example .env
  - composer install --no-interaction
  - npm install
  
script: 
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
 