
language: php

php:
  - 7.2

before_script:
  - composer self-update
  # - pear install pear/PHP_CodeSniffer
  # - phpenv rehash
  - nvm install --lts
  - npm install npm@latest -g
  - cd src  
  - cp .env.example .env
  - composer install --no-interaction
  - npm install
  
script: 
  # - phpcbf -v --standard=PSR2 app/Http/Controllers
  - npm run production
 
cache:
  directories:
    - node_modules
    - vendor